title: Fellowship Digital Ministry
description: Search sermon content and explore sermon analytics
baseurl: ""
url: "https://fellowship-digital-ministry.github.io"
theme: minima
plugins: []
markdown: kramdown

# Custom settings
api_url: "https://sermon-search-api-8fok.onrender.com"
church_website: "https://fbcministries.net/"