title: Fellowship Digital Ministry
description: Search sermon content and explore sermon analytics
baseurl: ""
url: "https://fellowship-digital-ministry.github.io"
theme: minima
plugins: []
markdown: kramdown

# Include the Bible KJV data in the built site
include:
  - _data/Bible-kjv-master

# Custom settings
api_url: "https://sermon-search-api-8fok.onrender.com"  # Make sure this URL is correct and without trailing slash
church_website: "https://fbcministries.net/"

# CORS settings - these are applied in Jekyll's front matter processing
# but you'll need to ensure your API allows these origins
cors_enabled: true
