name: Generate Sermon Analytics

on:
  schedule:
    # Run once a week on Sunday at 2 AM
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual trigger from GitHub UI

jobs:
  generate-analytics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv httpx
      
      - name: Process existing metadata from API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          python scripts/process_existing_metadata.py
          
      - name: Generate analytics data
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          python scripts/generate_analytics.py
          
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/analytics/*.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update sermon analytics data [skip ci]" && git push)