name: Generate Sermon Analytics

on:
  schedule:
    # Run once a week on Sunday at 2 AM
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual trigger from GitHub UI

jobs:
  generate-analytics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv httpx
      
      - name: Run incremental analytics generation
        env:
          API_URL: ${{ secrets.API_URL }}
          METADATA_DIR: ${{ github.workspace }}/_data/metadata
        run: |
          # Create metadata directory
          mkdir -p $METADATA_DIR
          
          # First, check if we can access the metadata repository
          if [ -n "${{ secrets.METADATA_REPO }}" ]; then
            echo "Trying to fetch metadata from external repository"
            git clone ${{ secrets.METADATA_REPO }} metadata_repo
            if [ -d "metadata_repo/transcription/metadata" ]; then
              echo "Copying metadata files"
              cp -r metadata_repo/transcription/metadata/* $METADATA_DIR/
            fi
          else
            echo "No metadata repository configured. Using API data only."
          fi
          
          # Run the incremental analytics script
          python scripts/incremental_analytics.py
          
          # Copy data to assets directory for GitHub Pages
          python scripts/copy_analytics_data.py
          
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/analytics/*.json assets/data/analytics/*.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update sermon analytics data [skip ci]" && git push)