name: Generate Sermon Analytics

on:
  schedule:
    # Run once a week on Sunday at 2 AM
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual trigger from GitHub UI

jobs:
  generate-analytics:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
        
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv httpx
      
      - name: Run incremental analytics generation
        env:
          API_URL: ${{ secrets.API_URL && 'https://' }}${{ secrets.API_URL }}
          METADATA_DIR: ${{ github.workspace }}/_data/metadata
        run: |
          # Create metadata directory
          mkdir -p $METADATA_DIR
          
          # First, check if we can access the metadata repository
          if [ -n "${{ secrets.METADATA_REPO }}" ]; then
            echo "Trying to fetch metadata from external repository"
            git clone ${{ secrets.METADATA_REPO }} metadata_repo
            if [ -d "metadata_repo/transcription/metadata" ]; then
              echo "Copying metadata files"
              cp -r metadata_repo/transcription/metadata/* $METADATA_DIR/
            fi
          else
            echo "No metadata repository configured. Using API data only."
          fi
          
          # Create sample data to get things started
          python scripts/copy_analytics_data.py
          
          # Run the incremental analytics script
          python scripts/incremental_analytics.py
          
      - name: Commit and push if changes
        run: |
          # Pull the latest changes from remote
          git pull --rebase origin main
          
          git add _data/analytics/*.json assets/data/analytics/*.json
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update sermon analytics data [skip ci]"
            
            # Push changes
            git push
          fi